---
title: "Measuring Political Freedom Around the World"
subtitle: "Sabrina Ball, Joe Despres, Joe Sigler, Jacob Haywood"
date: "Last compiled `r format(Sys.time(), '%H:%M')`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    mathjax: null
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
source(here::here("R", "regression.R"))
options(htmltools.dir.version = FALSE, echo = FALSE)
```

# Introduction
- political freedom as a function of 
- variables




---
```{r echo=FALSE}
subsets %>% 
  mutate_if(is.numeric, round, 3) %>% 
  rename(a_rsq = adj.r.squared) %>% 
  select(df, a_rsq, model) %>% 
  arrange(desc(a_rsq)) %>% 
DT::datatable(fillContainer = FALSE, options = list(pageLength = 3))
```

---
# Model

```{r}
# equatiomatic::extract_eq(model = model_df5, intercept = "beta", terms_per_line = 1)
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML"></script>
$$ 

\operatorname{polrights\_fh} = \beta_{0} + \beta_{1}(\operatorname{corruption\_perception\_index\_cpi}) + \beta_{2}(\operatorname{edu\_exp\_gdp\_per\_person}) + \beta_{3}(\operatorname{life\_expectancy\_years}) + \beta_{4}(\operatorname{military\_spending\_pct\_of\_gdp}) + \beta_{5}(\operatorname{murder\_per\_mil\_people}) + \epsilon
 
$$


---

# Model

---
# Conclusions
