---
title             : "Identifying Factors That Affect Political Freedom Within the OECD"
shorttitle        : "Political Freedom Within the OECD"

author: 
  - name          : "Joe Despres"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
  - name          : "Sabrina Ball"
    affiliation   : "1"
  - name          : "Jacob?"
    affiliation   : "1"
  - name          : "Joe Sigler"
    affiliation   : "1"


affiliation:
  - id            : "1"
    institution   : "Michigan State University"


  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
r_refs("r-references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

Using @Gapminder

## Introduction/Motivation

## Results

## Conclusion

\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup
